# Generated by Django 4.2.10 on 2024-03-13 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillsApp', '0002_colleague_delete_logmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Equipment', 'Equipment'), ('Software', 'Software')], max_length=100)),
                ('description', models.CharField(blank=True, max_length=350)),
                ('date_raised', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=100, null=True)),
                ('assignee', models.CharField(choices=[('Development Team', 'Development Team'), ('Management', 'Management'), ('Product Owner', 'Product Owner'), ('Suppliers', 'Suppliers')], max_length=100, null=True)),
                ('status', models.CharField(choices=[('Triage', 'Triage'), ('Resolution', 'Resolution'), ('Resolved', 'Resolved')], max_length=100, null=True)),
                ('colleague', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skillsApp.colleague')),
                ('keyword', models.ManyToManyField(to='skillsApp.keyword')),
            ],
        ),
    ]
