# Generated by Django 4.2.10 on 2024-03-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsApp', '0003_keyword_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colleague',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='colleague',
            name='colleagueID',
        ),
        migrations.RemoveField(
            model_name='colleague',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='colleague',
            name='jobfamily',
        ),
        migrations.RemoveField(
            model_name='colleague',
            name='status',
        ),
        migrations.RemoveField(
            model_name='colleague',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='date_raised',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='incident',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='title',
        ),
        migrations.AddField(
            model_name='colleague',
            name='date_joined',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='colleague',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='colleague',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
