# Generated by Django 4.2.10 on 2024-03-13 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skillsApp', '0005_colleague_colleagueid_colleague_jobfamily_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assignee_team',
            field=models.CharField(choices=[('Development Team', 'Development Team'), ('Management', 'Management'), ('Supplier', 'Supplier'), ('Colleague for review', 'Colleague for review'), ('Unassigned', 'Unassigned')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Software', 'Software'), ('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Headphones', 'Headphones'), ('Monitor', 'Monitor'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Other', 'Other')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='date_raised',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='incident',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='recreate',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Triage', 'Triage'), ('Open', 'Open'), ('Rejected', 'Rejected'), ('Fix in Progress', 'Fix in Progress'), ('Resolution', 'Resolution'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='summary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
