# Generated by Django 4.2.10 on 2024-03-19 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skillsApp', '0006_ticket_assignee_team_ticket_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleague',
            name='user',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
